title: Young Min Jung
email: james09756@gmail.com
description: >-
  KAIST undergraduate student exploring how technology can enhance human wisdom and well-being
baseurl: ""
url: "https://memorialStar.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Exclude files from processing
exclude:
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/